version: '2'

services:

  laravel:
    image: my_laravel:1.4
    volumes:
      - /var/www/html/docker/laravelproject:/var/www/html/laravelproject

  webserver:
    image: nginx
    volumes:
      - ./laravelProject.conf:/etc/nginx/conf.d/laravelProject.conf
    ports:
      - "8080:80"
  
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=ambab
      - MYSQL_PASSWORD=123456
    volumes:
      - myData:/var/lib/mysql

volumes:
  myData: